language: python
python:
  - "3.6"

notifications:
  email: false

install:
  - sudo apt-get update
  - sudo apt-get install mpich
  - pip install coverage codecov mpi4py
  - python setup.py install

script:
  - coverage run -m lsga.tests.test_all
  # Test parallel running.
  - mpirun -np 2 python -m lsga.tests.test_all
  # Upload test coverage report
  - codecov

